// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input v189fe9,
 input v59b691,
 input vbd2a31,
 output v446f52,
 output v032f70,
 output v813582,
 output v0b7996,
 output v20d1ea,
 output v631b76,
 output vfa6868,
 output v27382b,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 assign v446f52 = w0;
 assign v032f70 = w1;
 assign v813582 = w2;
 assign v0b7996 = w3;
 assign v20d1ea = w4;
 assign v631b76 = w5;
 assign vfa6868 = w6;
 assign v27382b = w7;
 assign w8 = v189fe9;
 assign w9 = vbd2a31;
 assign w10 = v59b691;
 main_vafeddf vafeddf (
  .Ch1(w0),
  .Ch2(w1),
  .Ch3(w2),
  .Ch4(w3),
  .Ch5(w4),
  .Ch6(w5),
  .Ch7(w6),
  .Ch8(w7),
  .PPM_inv(w8),
  .clk(w9),
  .reset(w10)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- PPM_8Asic  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Módulo exportado he importado con include tras modificar unos pocos detalles
/*-------------------------------------------------*/

module main_vafeddf (
 input PPM_inv,
 input reset,
 input clk,
 output Ch1,
 output Ch2,
 output Ch3,
 output Ch4,
 output Ch5,
 output Ch6,
 output Ch7,
 output Ch8
);
 
 //@include Module_Decoder_8bits_ASIC.v
 
 DecoderPPM8 MyDecoderPPM_8(.v35fe10(PPM_inv),.v85e55a(reset), .v357ff7(clk),
                .v980ce1(Ch1), .v5ad277(Ch2), .v9c8ff5(Ch3),
                .v755ffa(Ch4), .v9653af(Ch5), .vc74257(Ch6),
                .vd84530(Ch7), .va741a7(Ch8));
                
endmodule
